#!/usr/bin/env python3
"""Generate DEC-0004's enumerated effects (D37).

Deprecates the story-scoped acceptance specifications of closed stories. Those
atoms are not coverage gaps — they are completed lives: ONT-045 says a
story-scoped spec's lifetime tracks its story, their stories closed with evidence,
and holding them in `ratified` forever misreports finished work as missing
coverage.

Closed-ness is read from the tracker (ONT-044), following the DEC-0003 precedent —
never from a list maintained beside it, which would be a second source of truth for
the same fact.

    python3 tools/gen_dec0004.py --closed STORY-0001 STORY-0003 STORY-0004 STORY-0008

Note for a future consolidation: this shares its shape with gen_dec0003.py. Two
generators is tolerable; a third should become one parameterised tool, or the
duplication becomes the very defect the corpus keeps ruling against.
"""
import argparse
import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from atom_lint import corpus_digest, lint  # noqa: E402
from paths import CORPUS, SCHEMA  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--closed", nargs="+", required=True)
    ap.add_argument("--out", default=str(CORPUS / "DEC-0004.md"))
    a = ap.parse_args()

    atoms, errors = lint([str(CORPUS)], str(SCHEMA))
    if errors:
        print(f"refusing to generate against a red corpus: {len(errors)} finding(s)")
        for e in errors[:5]:
            print("  •", e)
        return 1

    digest = corpus_digest(atoms)
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    closed = set(a.closed)

    targets, skipped = [], []
    for aid, (atom, _src, _body) in sorted(atoms.items()):
        if atom.get("type") != "specification":
            continue
        if atom.get("story_ref") not in closed:
            continue
        if "acceptance-criterion" not in (atom.get("tags") or []):
            continue
        (targets if atom.get("state") == "ratified" else skipped).append(
            (aid, atom.get("state")))

    lines = [
        "# DEC-0004 — Two meters, two jobs; completed acceptance retired",
        "",
        "Generated by `tools/gen_dec0004.py` against a named corpus digest and signed",
        "by the owner's merge. The second exercise of the ceremony tooling, this time on",
        "the amendment path rather than the activation path.",
        "",
        "The amendments this decision authorizes are already written into the corpus and",
        "carry `authorized_by: DEC-0004`:",
        "",
        "- **DOC-0000 v1.1.0** — ONT-080 gains `unbound_claims` as the coverage meter and",
        "  restates launch readiness in terms of it; ONT-080a explains why two claim",
        "  meters are needed and why `dangling_claims` cannot be the coverage one;",
        "  ONT-060's table gains the `ratified → deprecated` row this decision's effects",
        "  depend on.",
        "- **DOC-0002 v0.1.2** — PA-022's done-test cites `unbound_claims`. Draft, so",
        "  amended directly.",
        "",
        f"Effects, computed at `corpus@{digest}`: {len(targets)} story-scoped acceptance",
        "specifications of the closed stories "
        f"{', '.join(sorted(closed))} move `ratified → deprecated`. Closed-ness read",
        "from the tracker (ONT-044).",
        "",
        "<!-- atom:begin id=DEC-0004 -->",
        "```yaml",
        "id: DEC-0004",
        "type: decision",
        "scope: platform",
        "state: proposed",
        "version: 0.1.0",
        f'instantiated_at: "{now}"',
        "author: agent-worker-dec-0004",
        "authorized_by: null",
        'title: "Two meters, two jobs; completed acceptance retired"',
        "tags: [meters, amendment, machine-enumerated]",
        "question: >",
        "  Which query measures whether the law is wired up, and what becomes of the",
        "  acceptance criteria of stories that have already closed with evidence?",
        "outcome: >",
        "  Two meters with two jobs. unbound_claims — ratified claims no active rule",
        "  binds — is the coverage number and the one launch readiness cites;",
        "  dangling_claims stays as a drift guard, structurally zero at activation and",
        "  meaningful only when a rule is removed from under a live claim. The",
        "  acceptance specifications of closed stories are retired to deprecated: their",
        "  stories completed with evidence, and ONT-045 ties their lifetime to those",
        "  stories, so holding them in ratified misreports finished work as missing",
        "  coverage. ONT-060 gains the ratified to deprecated edge that exit requires.",
        'process_ref: "git-merge:DEC-0004"',
        "effects:",
        "  - { target: DEC-0004, transition: ratified }",
    ]
    for aid, _state in targets:
        lines.append(f"  - {{ target: {aid}, transition: deprecated }}")
    lines += [
        "```",
        f"Enumerated against `corpus@{digest}` at {now}.",
        "",
        "After this decision the coverage meter reads the honest remainder: the",
        "human-check claims awaiting a human-evidence process. The three controls held",
        "on ONT-033 grounds stay visible until their suites exist — CTRL-0005 and",
        "CTRL-0006 arrive with the spawn contract, CTRL-0008 with the index suite — so",
        "every number on the standing report means exactly one thing.",
        "<!-- atom:end id=DEC-0004 -->",
        "",
    ]
    pathlib.Path(a.out).write_text("\n".join(lines))
    print(f"wrote {a.out}")
    print(f"  deprecations: {len(targets)}")
    for aid, _ in targets:
        print(f"    {aid}")
    if skipped:
        print(f"  acceptance specs of closed stories not in `ratified`: {len(skipped)}")
        for aid, st in skipped:
            print(f"    {aid} ({st})")
    print(f"  digest: corpus@{digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
